## makeCacheMatrix and cacheSolve calculate inverse of a matrix and
## caches the answer (inverse) 

## this function generates a list where
## "set" sets the matrix value,
## "get" gets/extracts the matrix value,
## "setinverse" sets the value of inverse matrix, and
## "getinverse" gets/extracts the value of inverse matrix 

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function (y) {
    x <<- y
  }
  get <- function () { x }
  setinverse <- function(inverse) { m <<- inverse}
  getinverse <- function() { m }
  list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## this function uses the list generated by makeCacheMatrix: 
## If a matrix that has been previously inputted to the function
## has been inputted again, the cached value of inverse is returned.
## Otherwise, the inverse of requested matrix is calculated and presented.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {message("getting cached data")
    return(m)}
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}